#!/bin/sh

cd ~ && touch .bash_aliases && echo "if [ -f ~/.bash_aliases ]; then
. ~/.bash_aliases
fi" >> .bashrc && rm -Rf flutter && mkdir flutter && cd flutter && mkdir flutter-dev && mkdir flutter-stable && mkdir flutter-master && mkdir flutter-beta && cd ~/flutter/flutter-dev && git clone https://github.com/flutter/flutter.git -b dev --depth 1 && cd ~/flutter/flutter-master && git clone https://github.com/flutter/flutter.git -b master --depth 1 && cd ~/flutter/flutter-beta && git clone https://github.com/flutter/flutter.git -b beta --depth 1 && cd ~/flutter/flutter-stable && git clone https://github.com/flutter/flutter.git -b stable --depth 1 && cd ~ && rm .bash_aliases &&  echo "alias flutter='~/flutter/flutter-dev/flutter/bin/flutter' 
alias flutterm='~/flutter/flutter-master/flutter/bin/flutter' 
alias flutterb='~/flutter/flutter-beta/flutter/bin/flutter' 
alias flutters='~/flutter/flutter-stable/flutter/bin/flutter'">> .bash_aliases && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
-y && $HOME/flutter/flutter-dev/flutter/bin/flutter config --enable-web && $HOME/flutter/flutter-dev/flutter/bin/flutter config --enable-linux-desktop && $HOME/flutter/flutter-dev/flutter/bin/flutter precache && $HOME/flutter/flutter-dev/flutter/bin/flutter doctor -v && $HOME/flutter/flutter-stable/flutter/bin/flutter config --enable-web && $HOME/flutter/flutter-stable/flutter/bin/flutter config --enable-linux-desktop && $HOME/flutter/flutter-stable/flutter/bin/flutter precache && $HOME/flutter/flutter-stable/flutter/bin/flutter doctor -v && $HOME/flutter/flutter-beta/flutter/bin/flutter config --enable-web && $HOME/flutter/flutter-beta/flutter/bin/flutter config --enable-linux-desktop && $HOME/flutter/flutter-beta/flutter/bin/flutter precache && $HOME/flutter/flutter-beta/flutter/bin/flutter doctor -v && $HOME/flutter/flutter-master/flutter/bin/flutter config --enable-web && $HOME/flutter/flutter-master/flutter/bin/flutter config --enable-linux-desktop && $HOME/flutter/flutter-master/flutter/bin/flutter precache && $HOME/flutter/flutter-master/flutter/bin/flutter doctor -v && flutter doctor --android-licenses

